### ISSUE TITLE
Dynamic Tempo

### ISSUE THREAD

**Issue by yk0n9** [bhaeussermann/MidiReader#1]
`MidiReader reader = new MidiReader("[ path to your midi file that contains lyrics ]");
try
{
    MidiFileInfo midiFileInfo = reader.getMidiFileInfo();
    for (MidiEvent nextEvent : reader)
    {
        long delayMillis = nextEvent.getDeltaTime() * midiFileInfo.getMicrosecondsPerTick() / 1000;
        Thread.sleep(delayMillis);
        if ((nextEvent instanceof MetaMidiEvent) && (((MetaMidiEvent) nextEvent).getMetaEventType()==MetaEventType.LYRIC))
            System.out.print(((MetaMidiEvent) nextEvent).getContentAsString());
    }
}
finally
{
    try
    {
        reader.close();
    } 
    catch (IOException e) {}
}`

Can I be optimized for each iteration and will reset Tempo,
This class library only sets TEMPO at a time at the beginning, which will cause the rhythm of the MIDI output of the change of TEMPO.

**Comment by bhaeussermann** [comment]
Are you saying that the library does not account for changes in the tempo of the song since it assumes a constant tempo?

Note that the enum `MetaEventType` has a value `SET_TEMPO` which should be emitted whenever the song changes tempo, so your program could look for those events and use that to keep track of the current tempo.

**Comment by yk0n9** [comment]
> Are you saying that the library does not account for changes in the tempo of the song since it assumes a constant tempo?
> 
> Note that the enum `MetaEventType` has a value `SET_TEMPO` which should be emitted whenever the song changes tempo, so your program could look for those events and use that to keep track of the current tempo.

I found that iterating like this doesn't output a MetaMidiEvent, it just outputs a NoteMidiEvent. so i can't change it

midireader.midievent.NoteMidiEvent[deltaTime=478;totalTime=478][channel=Tr 1 Ch 0;noteNumber=62;noteFrequency=293.66476791740746;velocity=100]
midireader.midievent.NoteMidiEvent[deltaTime=1;totalTime=479][channel=Tr 2 Ch 1;noteNumber=57;noteFrequency=219.9999999999999;velocity=100]
midireader.midievent.NoteMidiEvent[deltaTime=0;totalTime=479][channel=Tr 3 Ch 2;noteNumber=62;noteFrequency=293.66476791740746;velocity=40]
midireader.midievent.NoteMidiEvent[deltaTime=1;totalTime=480][channel=Tr 2 Ch 1;noteNumber=50;noteFrequency=146.83238395870364;velocity=100]
midireader.midievent.NoteMidiEvent[deltaTime=32;totalTime=512][channel=Tr 2 Ch 1;noteNumber=45;noteFrequency=109.99999999999989;velocity=100]
midireader.midievent.NoteMidiEvent[deltaTime=28;totalTime=540][channel=Tr 2 Ch 1;noteNumber=50;noteFrequency=146.83238395870364;velocity=0]
midireader.midievent.NoteMidiEvent[deltaTime=1;totalTime=541][channel=Tr 2 Ch 1;noteNumber=50;noteFrequency=146.83238395870364;velocity=100]

**Comment by bhaeussermann** [comment]
I can't tell off-hand why it would not emit the `SET_TEMPO` events. Having a quick look at [MidiTrackReader.java](https://github.com/bhaeussermann/MidiReader/blob/65e48441c60b9f7437eac3cfb10b63baf7e7e7de/src/midireader/MidiTrackReader.java#L270) I can see that the code does provide for those. Are you sure that your midi-stream actually does contain `SET_TEMPO` events?

Unfortunately, I haven't worked on the code for almost a century, and I don't have a Java working environment set up since I work mostly in .NET these days. You're welcome to debug the code. If you manage to find and fix a bug in it, I would be happy to review a pull request.
